# Set the platform to 15.0 to satisfy Firebase
platform :ios, '15.0'

# --- THE MISSING LINK ---
# This line tells the Mac to load the Flutter helper functions
load File.join(File.dirname(File.realpath(__FILE__)), 'Generated.xcconfig')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # This function is now defined because of the 'load' line above
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # This loop ensures every sub-plugin also targets iOS 15.0
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end